[package]
name = "stanrustlalrpop"
version = "0.1.0"
authors = ["Sean Talts <sean.talts@gmail.com>"]
build = "build.rs" # LALRPOP preprocessing

[dependencies]
lalrpop-util = "0.16.0"
regex = "0.2.0"
lazy_static = "1.1.0"

[build-dependencies]
lalrpop = "0.16.0"
